"""initial schema

Revision ID: 04cf546269d3
Revises: 
Create Date: 2026-09-18 19:33:58.205142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04cf546269d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('simulation_run_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_x_km', sa.Float(), nullable=False),
    sa.Column('location_y_km', sa.Float(), nullable=False),
    sa.Column('reachability_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('simulation_run_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_x_km', sa.Float(), nullable=False),
    sa.Column('location_y_km', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('final_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('simulation_run_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_x_km', sa.Float(), nullable=False),
    sa.Column('location_y_km', sa.Float(), nullable=False),
    sa.Column('base_prep_minutes', sa.Float(), nullable=False),
    sa.Column('prep_time_stddev_minutes', sa.Float(), nullable=False),
    sa.Column('rush_hour_multiplier', sa.Float(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('final_backlog', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_run_id', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('cancelled_count', sa.Integer(), nullable=False),
    sa.Column('in_flight_count', sa.Integer(), nullable=False),
    sa.Column('late_delivered_count', sa.Integer(), nullable=False),
    sa.Column('late_rate', sa.Float(), nullable=False),
    sa.Column('failure_rate', sa.Float(), nullable=False),
    sa.Column('cancellation_rate', sa.Float(), nullable=False),
    sa.Column('avg_delay_minutes', sa.Float(), nullable=False),
    sa.Column('p50_delay_minutes', sa.Float(), nullable=False),
    sa.Column('p95_delay_minutes', sa.Float(), nullable=False),
    sa.Column('intervention_count', sa.Integer(), nullable=False),
    sa.Column('intervention_rate', sa.Float(), nullable=False),
    sa.Column('total_intervention_cost', sa.Float(), nullable=False),
    sa.Column('failure_reason_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cancellation_reason_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('simulation_run_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('promised_delivery_time', sa.DateTime(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('is_perishable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('created', 'confirmed', 'assigned', 'en_route_to_merchant', 'arrived_at_merchant', 'picked_up', 'en_route_to_customer', 'delivered', 'failed', 'cancelled', name='order_status'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.Enum('merchant_out_of_stock', 'no_driver_available', 'customer_changed_mind', name='cancellation_reason'), nullable=True),
    sa.Column('failure_reason', sa.Enum('driver_never_arrived', 'never_picked_up', 'damaged_or_spoiled', 'customer_unreachable', name='failure_reason'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('delivery_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('delivery_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.Enum('order_created', 'order_confirmed', 'order_cancelled', 'driver_assigned', 'driver_en_route_to_merchant', 'driver_arrived_at_merchant', 'order_picked_up', 'driver_en_route_to_customer', 'order_delivered', 'order_failed', 'driver_went_offline', name='event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('delivery_id', sa.String(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('overall_risk_score', sa.Float(), nullable=False),
    sa.Column('predicted_failure_type', sa.Enum('late_delivery', 'never_picked_up', 'driver_never_arrived', 'damaged_or_spoiled', 'customer_unreachable', 'no_driver_available', name='predicted_failure_type'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('predicted_delay_minutes', sa.Float(), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervention_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('delivery_id', sa.String(), nullable=True),
    sa.Column('risk_assessment_id', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('chosen', sa.Enum('do_nothing', 'update_eta', 'notify_customer', 'notify_merchant', 'merchant_escalation', 'offer_credit', 'reassign_driver', name='intervention_type'), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intervention_decisions')
    op.drop_table('risk_assessments')
    op.drop_table('delivery_events')
    op.drop_table('deliveries')
    op.drop_table('orders')
    op.drop_table('simulation_metrics')
    op.drop_table('merchants')
    op.drop_table('drivers')
    op.drop_table('customers')
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
    # Manually added: autogenerate's drop_table() doesn't emit DROP TYPE for
    # the native Postgres enums those tables' columns used, so a downgrade
    # followed by an upgrade would otherwise fail with "type already exists".
    bind = op.get_bind()
    sa.Enum(name="intervention_type").drop(bind, checkfirst=True)
    sa.Enum(name="predicted_failure_type").drop(bind, checkfirst=True)
    sa.Enum(name="event_type").drop(bind, checkfirst=True)
    sa.Enum(name="failure_reason").drop(bind, checkfirst=True)
    sa.Enum(name="cancellation_reason").drop(bind, checkfirst=True)
    sa.Enum(name="order_status").drop(bind, checkfirst=True)
